name: java-ci
on : [push]
jobs:
    sonar-lint:
        runs-on: ubuntu-latest
        steps:
            - name: setup-java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version:  21
            - name: verify java installation
              run: |
                   java -version
            - name: project checkout
              uses: actions/checkout@v4
            - name: change project directory
              run: |
                   pwd
            - name: maven verify
              run:  |
                    mvn verify
            - name: run sonarqube
              run:  |
                    mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=karth06_spring-app-cicd-demo -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
              env:  
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: upload test-coverage
              uses: actions/upload-artifact@v4
              with:
                name: jacoco-report
                path: target/site/jacoco/jacoco.xml
              
