name: java-ci
on : [push]
jobs:
    sonar-lint:
        runs-on: ubuntu-latest
        steps:
            - name: setup-java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version:  21
            - name: verify java installation
              run: |
                   java -version
            - name: project checkout
              uses: actions/checkout@v4
            - name: change project directory
              run: |
                   cd /spring-app-cicd-demo
                   pwd
            - name: maven verify
              run:  |
                    mvn verify